### ISSUE TITLE
could you update the link of Google Drive?

### ISSUE THREAD

**Issue by ForrestPi** [OSVAI/GridConv#1]
Hi, could you update the link of Google Drive?

**Comment by YaoAnbang** [comment]
We just tried again, and the links are valid now.

**Comment by ForrestPi** [comment]
@YaoAnbang  
Hi, 
Get preprocessed h36m.zip ([Google Drive](https://github.com/OSVAI/GridConv/blob/main))   
could you check this link?

**Comment by YaoAnbang** [comment]
It should work now. Please try it again.
