### ISSUE TITLE
Error loading dataset

### ISSUE THREAD

**Issue by wangdazhong1112** [OSVAI/GridConv#3]
When I try to run, there is a problem with the loading prompt.I also have a question that other 2D attitude estimators, such as CPN and SH, can be selected in the input parameters, but the given dataset only includes the values of gt and HRNet. Is it convenient to provide data from other 2D attitude estimators?

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 0: 
![image](https://github.com/OSVAI/GridConv/assets/119930848/6fbf79ad-48b9-4c06-a7b8-462f5d000e9d)

**Comment by TigerWzWings** [comment]
I've got same problem. That's easy to figure out, the error information have told, you could try to change another Unicode where the function be used"result = unpickled.load()". I've tried use Latin1 or other Unicode and that's worked.

**Comment by TigerWzWings** [comment]
> When I try to run, there is a problem with the loading prompt.I also have a question that other 2D attitude estimators, such as CPN and SH, can be selected in the input parameters, but the given dataset only includes the values of gt and HRNet. Is it convenient to provide data from other 2D attitude estimators?
> 
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 0: ![image](https://user-images.githubusercontent.com/119930848/269323604-6fbf79ad-48b9-4c06-a7b8-462f5d000e9d.png)

I've got same problem. That's easy to figure out, the error information have told, you could try to change another Unicode where the function be used"result = unpickled.load()". I've tried use Latin1 or other Unicode and that's worked.

**Comment by kyang-06** [comment]
> > When I try to run, there is a problem with the loading prompt.I also have a question that other 2D attitude estimators, such as CPN and SH, can be selected in the input parameters, but the given dataset only includes the values of gt and HRNet. Is it convenient to provide data from other 2D attitude estimators?
> > UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 0: ![image](https://user-images.githubusercontent.com/119930848/269323604-6fbf79ad-48b9-4c06-a7b8-462f5d000e9d.png)
> 
> I've got same problem. That's easy to figure out, the error information have told, you could try to change another Unicode where the function be used"result = unpickled.load()". I've tried use Latin1 or other Unicode and that's worked.

Yes, Pytorch > 1.4 may raise this error. You may try this
`cur_data_2d = torch.load(os.path.join(data_path, data_2d_file), encoding='Latin1')`
