### ISSUE TITLE
Have you set any seed in your experiment?

### ISSUE THREAD

**Issue by cocoshe** [OSVAI/GridConv#6]
I think it the reason why I have difficulty on reproducing the result.

**Comment by Clouc-Catkin** [comment]
> I think it the reason why I have difficulty on reproducing the result.

Hey, I have same problem to reproducing the result. I think that the training log proviede by the author in another closed issue 4 is somewhat strange. As starting from the epoch 79, the train loss dropped from 0.013 to 0.007, and from epoch 66 to epoch 70, train loss varies from 0.0111 to 0008 to 0.0101. I reproduced some 3d human pose estimation works previously. I haven't seen this kind of change before. In general, if test loss descends, the error MPJPE should also descend. But in epoch 71, test loss is 0.0031, error MPJPE is 78mm, however, in epoch 80, test loss is 0.0060, error MPJPE is 72mm > 78mm in epoch 71.
